version: '3.8'

services:
  ai-agents-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_URL: ${API_URL:-http://localhost:8000}
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Example backend service (uncomment if you have a backend)
  # api:
  #   image: your-api-image:latest
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL}
  #   restart: unless-stopped

networks:
  default:
    name: ai-agents-network